### ISSUE TITLE
Missing doc on how to run the hub

### ISSUE THREAD

**Issue by ajunge** [decentralized-identity/hub-node-core#5]
Don't know how to run the hub. Maybe a script for `npm start`

**Comment by thehenrytsai** [comment]
Hi Andres,

hub-node-core is intended to be a core **library** to be used to instantiate an instance of a Hub, so no `npm start` here. hub-node-reference repo in this case is supposed to provide that reference usage of this library.

However hub-node-reference current is still a work in progress, when it's ready a README will be added.

With your permission I will close this this issue, and open a new one in this repo to create a README file to rectify this confusion.

**Comment by ajunge** [comment]
Please do so.

Gracias

**Comment by thehenrytsai** [comment]
[Issue](https://github.com/decentralized-identity/hub-node-core/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) added.
